### ISSUE TITLE
Create Contact Page

### ISSUE THREAD

**Issue by DreamsOfImran** [DreamsOfImran/TimesOfInternet#1]
Need to create a contact page with basic address information with an email form.
Can get those details from "https://dreamsofimran.in"

**Comment by oneofthedevs** [comment]
Do you have a rough idea of what you want the design to look like?

**Comment by DreamsOfImran** [comment]
There's already a separate file under the view folder with a basic template with it. You can work on top of that.

**Comment by Jaagrav** [comment]
Hey @DreamsOfImran , I am interested in doing this, I noticed that you don't have a Google Maps API key, it also needs billing so instead I am embedding a Chennai map in place of the Google Javascript Map. I hope that'd work??

**Comment by Jaagrav** [comment]
Please review the PR I made, #8 
Changes I made:
- Added and imported 'react-iframe' in ContactUsPage.js
- Added Google Maps Embed API key
- Added Google Maps depicting the Marina Beach, Chennai
- Changed Router Component and imported ContactUsPage in index.js

**Comment by DreamsOfImran** [comment]
@Jaagrav Thank you for your contribution.
