### ISSUE TITLE
Create About Page

### ISSUE THREAD

**Issue by DreamsOfImran** [DreamsOfImran/TimesOfInternet#2]
Need to create about page with basic information of the application and also basic information about me.

Can find those details at "https://dreamsofimran.in"

**Comment by nidhi-bhanushali** [comment]
Is this done or still up for grabs?

**Comment by DreamsOfImran** [comment]
@nidhi-bhanushali Please go ahead with your changes. I'll assign this to you.

**Comment by nidhi-bhanushali** [comment]
Are there specific images / color-scheme you want me to use?

**Comment by DreamsOfImran** [comment]
There is a separate view folder for this [About](https://github.com/DreamsOfImran/TimesOfInternet/blob/master/src/views/AboutUsPage/AboutUsPage.js) page.
Take a look and work on that file.
For image/color-scheme, It's up to your creativity

**Comment by nidhi-bhanushali** [comment]
Sure , okay!

**Comment by nidhi-bhanushali** [comment]
I've made a PR for this issue , kindly check!

**Comment by DreamsOfImran** [comment]
@nidhi-bhanushali Merged the PR #4 you made.
Thanks again for your contribution.
If you want you can also pick up the contact page #1
